//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWinForms.ServiceReferenceGreeter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceGreeter.IGreeterService")]
    public interface IGreeterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGreeterService/Greet", ReplyAction="http://tempuri.org/IGreeterService/GreetResponse")]
        string Greet(string who);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGreeterService/Greet", ReplyAction="http://tempuri.org/IGreeterService/GreetResponse")]
        System.Threading.Tasks.Task<string> GreetAsync(string who);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGreeterServiceChannel : DemoWinForms.ServiceReferenceGreeter.IGreeterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GreeterServiceClient : System.ServiceModel.ClientBase<DemoWinForms.ServiceReferenceGreeter.IGreeterService>, DemoWinForms.ServiceReferenceGreeter.IGreeterService {
        
        public GreeterServiceClient() {
        }
        
        public GreeterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GreeterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GreeterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GreeterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Greet(string who) {
            return base.Channel.Greet(who);
        }
        
        public System.Threading.Tasks.Task<string> GreetAsync(string who) {
            return base.Channel.GreetAsync(who);
        }
    }
}
